### ISSUE TITLE
HTTParty

### ISSUE THREAD

**Issue by PwBwolf** [PwBwolf/Projecct-four#1]
MagicSeaWeed(API I am using) gave me back key and when I run it in httparty I do not get anything back. They also provided in my email a example request with my api key in it that does not work. Should I assume that the API key they gave me is broke? I followed the steps for httparty and when I try and view the body it is empty 

Also I think I may need a new table based on reviewing this API, I would like to run it past you.

**Comment by jkonowitch** [comment]
Hmmm. can you paste the example code you used?

**Comment by PwBwolf** [comment]
[7] pry(main)> response = HTTParty.get("http://magicseaweed.com/api/2b26d1b26fa8a1bf5c3c5c1b08503f83d9cb14bf/forecast/?spot_id=3683")

=> nil
[8] pry(main)> response.class
=> HTTParty::Response
[9] pry(main)> response.[0]
SyntaxError: unexpected '[', expecting '('
response.[0]
          ^
[9] pry(main)> response
=> nil
[10] pry(main)> response.body
=> ""
[11] pry(main)>

**Comment by PwBwolf** [comment]
email from them 

Hi,

Your API details are below:

Key: 2b26d1b26fa8a1bf5c3c5c1b08503f83d9cb14bf
Secret: 8e26fa150a29bcdba7376f90e84a2325f1a97788

Documentation can be found here: http://magicseaweed.com/developer/forecast-api

Here's an example URL showing the forecast for Newquay: http://magicseaweed.com/api/2b26d1b26fa8a1bf5c3c5c1b08503f83d9cb14bfforecast/?spot_id=1

Please let us know if there are any problems.

The API exists to add marine forecast information to your product. It’s not a license to replicate the locational database we’ve created on MSW. This locational data remains our intellectual property and thus we don't provide an API for this data. Additionally the API isn’t designed for the building of applications that replicate core functionality found on the MSW website and we reserve the right to terminate applications that do this.

Kind regards,
Eoghan

**Comment by PwBwolf** [comment]
That link just gives an error, I emailed them back I think there is something wrong with the key

**Comment by jkonowitch** [comment]
Yikes... I just tried and am also getting nothing back. I think that's an API issue

**Comment by jkonowitch** [comment]
I'd move on to other parts of that story. PS can you add me as a collaborator on your trello too if you haven't? Thanks man.

**Comment by PwBwolf** [comment]
Ok yea I have you on there already let me know if it does not come up because based on the documentation from that API reviewed I think I have to set up my database differently. I dont think I can do a search by name for a location current conditions. I need to know the location id before hand so that would require me having a table with locations and their corresponding MSW id so I can do the API GET when necessary. I was going to limit the app to just New Jersey if that is the case
