### ISSUE TITLE
DB:migration for image

### ISSUE THREAD

**Issue by PwBwolf** [PwBwolf/Projecct-four#2]
I tried to create a model that would store the image that was uploaded to an entry with the 'bytea' type becasue I read that was the best one for postresql. but when I went to go migrate the table I got an error I cannot seem to figure out 

== 20150604030621 CreateLocations: migrating ==================================
-- create_table(:locations)
   -> 0.1617s
== 20150604030621 CreateLocations: migrated (0.1619s) =========================

== 20150604032538 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0146s
== 20150604032538 CreateUsers: migrated (0.0147s) =============================

== 20150604033731 CreateJournals: migrating ===================================
-- create_table(:journals)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `bytea' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x007feccf85b5b0>/Users/peter/fourthProject/Projecct-four/Surfer_Log/db/migrate/20150604033731_create_journals.rb:10:in `block in change'
/Users/peter/fourthProject/Projecct-four/Surfer_Log/db/migrate/20150604033731_create_journals.rb:3:in `change'
NoMethodError: undefined method `bytea' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x007feccf85b5b0>
/Users/peter/fourthProject/Projecct-four/Surfer_Log/db/migrate/20150604033731_create_journals.rb:10:in `block in change'
/Users/peter/fourthProject/Projecct-four/Surfer_Log/db/migrate/20150604033731_create_journals.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by jkonowitch** [comment]
It's very tricky to try and store an actual image file in your DB. Are these pictures from users or the MSW API?

**Comment by PwBwolf** [comment]
I used binary instead based on some research but I am a little confused why bytea will not work on a migration, I am guessing because is a rails app?

**Comment by jkonowitch** [comment]
So the rails migration syntax probably does not recognize that column type. That said - this isn't a great way to handle image saving. I would go ahead and remove that column from your table at the moment and we can revisit when you get to the photo uploading story. At that point I can give you some direction on how to handle that. Make sense?

**Comment by PwBwolf** [comment]
They are from users, I am having all sorts of problems now though with it because
 I cannot connect to any of the databases that I created

**Comment by PwBwolf** [comment]
yes sure thats fine

**Comment by jkonowitch** [comment]
Yep - go ahead and remove that from your migration and it should work. Let me know!
