### ISSUE TITLE
Cannot get view to display database

### ISSUE THREAD

**Issue by PwBwolf** [PwBwolf/Projecct-four#4]

**Comment by jkonowitch** [comment]
Can you point to some code and the story you're working on? I don't understand the issue.

**Comment by PwBwolf** [comment]
nothing from the favorites table is appearing on my screen just the MVC of backbone really

**Comment by jkonowitch** [comment]
Can you point me to the code and the specific question you have? It's still fuzzy for me as to what the problem is.

**Comment by PwBwolf** [comment]
I am not even sure where the problem, its would be easier for me to just discuss it with you I think.
